
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module CSCE611_lab_alu(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

/* not connected */
logic  [31:0] NC_hi;
logic         NC_zero;

/* hex display */
logic  [31:0] hexoutput;

//=======================================================
//  Structural coding
//=======================================================

/* display drivers -- you should use the hex driver module you wrote for lab
 * 0. You may modify these lines if your module is named differently */
hexdriver h7 (hexoutput[31:28], HEX7);
hexdriver h6 (hexoutput[27:24], HEX6);
hexdriver h5 (hexoutput[23:20], HEX5);
hexdriver h4 (hexoutput[19:16], HEX4);
hexdriver h3 (hexoutput[15:12], HEX3);
hexdriver h2 (hexoutput[11:8],  HEX2);
hexdriver h1 (hexoutput[7:4],   HEX1);
hexdriver h0 (hexoutput[3:0],   HEX0);

/* ALU instance. lo connected to the hex displays, and op set by the keys */
alu alu0 (
	.a    (SW[17:9] ),
	.b    (SW[8:0]  ),
	.op   (KEY      ),
	.shamt(5'h0     ),
	.hi   (NC_hi    ),
	.lo   (hexoutput),
	.zero (NC_zero  )
);


endmodule
